export const userScheme = {
  id: true,
  login: true,
  name: true,
  email: true,
  role: true,
  categoryId: true,
  phone: true,
  birthdate: true,
  status: true,
  createdAt: true,
  updatedAt: true,
  firebaseToken: true,
  driverLicenseId: true,
};
